$ jqt: rhn xhk
$ rsh: frs pzl lsr
$ xhk: hfx
$ cmg: qnr nvd lhk
$ rhn: xhk bvb hfx
$ bvb: xhk hfx
$ pzl: lsr nvd
$ qnr: nvd
$ ntq: jqt hfx bvb xhk
$ nvd: lhk
$ lsr: lhk
$ rzs: qnr cmg lsr rsh
$ frs: qnr lhk lsr
⊜(⊃(□↘1|⊢)regex"\\w{3}")≠@\n.
⊃(∘|⊝⇌∧(⊂°□)⊙⇌)
⊃(≡(⍜°□⊗)⊙¤|⬚0↯⊂.:[]⧻⋅∘)
↥⍉.⬚0↥⬚0≡(°⊚°□)
Adj ← ⊚⊡
RemoveVisited ← ▽¬⊃∊∘
[0] []
⍢(
  ⊃(↘1|⊢)
  ⊙(
    ⊃(∘|⊂)
    ⊃(Adj ⊙⋅∘|⋅⊙∘)
    ⊃(RemoveVisited|⋅⊙∘)
  )
  ⊝⊂
| >0⧻
)
×-:⊃(⧻⋅⋅∘|.⧻;)
